version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: frontend-orbit-crm
    ports:
      - 3002:3000
    volumes:
      - .:/app
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
